### ISSUE TITLE
Hi

### ISSUE THREAD

**Issue by DusanCV** [LucasGGamerM/moshidon-nightly#1]
Hi Lucas, you are doing a great job with Moshidon! I don't have any problem to report, but I haven't found another way to send a message. If you have any contact, I have a few questions regarding your work on the app. You can contact me via email in my Bio. Greeting!

**Comment by LucasGGamerM** [comment]
You can ping me in the official Moshidon account at @moshidon@floss.social . I will be happy to talk to you there!

**Comment by DusanCV** [comment]
Great, thanks a lot! Then you can delete the "issue" so I don't spam github. :D

    četvrtak, 4. svibnja 2023. u 13:10:03 CEST, korisnik LucasGGamerM ***@***.***> napisao je:  
 
 


You can ping me in the official Moshidon account at @***@***.*** . I will be happy to talk to you there!
